cdwebv2:
  stage: deploy
  only:
    - master
  # when: manual
  variables:
    IMG_NAME: registry.fly.io/$CI_JOB_NAME:$CI_COMMIT_SHORT_SHA
    FLY_FILE: fly/$CI_JOB_NAME.toml
  script:
    - docker build -t $IMG_NAME .
    - docker push $IMG_NAME
    - fly deploy --detach -i "$IMG_NAME" -c $FLY_FILE
